// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jkvmnducafjvycrdgcph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imprdm1uZHVjYWZqdnljcmRnY3BoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI1NjA4MDksImV4cCI6MjA4ODEzNjgwOX0.s0mF4pmrILUaHmPb3F8RzSHtU8FwrC6lovF8JmrsZjY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});